name: kiding_frontend
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  video_player: ^2.8.3
  qr_code_scanner: ^1.0.1
  google_ml_kit: ^0.16.3
  image_picker: ^1.0.7
  # firebase_core: ^2.30.0
  # firebase_auth: ^4.19.1
  # firebase_database: ^10.5.1
  mysql_client: ^0.0.27
  mysql1: ^0.20.0
  http: ^1.2.1
  gif: ^2.3.0
  flutter_secure_storage: ^9.2.2
  flutter_qr_bar_scanner: ^3.0.2

  cupertino_icons: ^1.0.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/login/
    - assets/home/
    - assets/kikisday/
    - assets/space/
    - assets/mypage/
    - assets/exit/
    - assets/friends/
    - assets/ranking/

  fonts:
    - family: Nanum
      fonts:
        - asset: assets/fonts/nanum.ttf
    - family: NanumRegular
      fonts:
        - asset: assets/fonts/NanumSquareNeo-bRg.ttf
